name: Run Google Colab Notebook

on:
  schedule:
    - cron: '*/30 * * * *'  # 매 30분마다 실행 # 매일 오전 9시 실행 (UTC 기준, 한국시간 오전 9시는 '0 0 * * *'로 설정 필요)
  workflow_dispatch:  # 수동 실행 버튼 제공

jobs:
  run-colab:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          service_account_key: ${{ secrets.GOOGLE_CREDENTIALS }}
          export_default_credentials: true

      - name: Install dependencies
        run: pip install google-auth google-auth-oauthlib google-api-python-client

      - name: Execute Colab
        run: |
          curl -X POST -H "Authorization: Bearer $(gcloud auth print-access-token)" \
          https://colab.research.google.com/drive/1i0HFk5Kf9xUQI0Ub9vsmrLltQJRYf_nk/execute
